---
title: "Proyecto1_MineriaDatos"
author: "Alejandro Alvarez"
date: "3/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
Se importan las librerías y paquetes necesarios para procesar, graficar y ordenar los datos de las bases de datos
```{r library/package import, warning=FALSE}
install.packages('haven')
library(haven)

```
 
Se importan las bases de datos de 2010 - 2019 [10 en total] de sus respectivos archivos de SPSS
```{r}
data2010 <- read_sav('./db/2010.sav')
data2010
data2011 <- read_sav('./db/2011.sav')
data2011
data2012 <- read_sav('./db/2012.sav')
data2012
data2013 <- read_sav('./db/2013.sav')
data2013
data2014 <- read_sav('./db/2014.sav')
data2014
data2015 <- read_sav('./db/2015.sav')
data2015
data2016 <- read_sav('./db/2016.sav')
data2016
data2017 <- read_sav('./db/2017.sav')
data2017
data2018 <- read_sav('./db/2018.sav')
data2018
data2019 <- read_sav('./db/2019.sav')
data2019
```

